# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "console.fullname" . }}-mcmapplicationui
  labels:
    app: {{ template "console.name" . }}
    chart: {{ template "console.chart" . }}
    component: "mcmapplicationui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "console.name" . }}
    helm.sh/chart: {{ template "console.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "console.name" . }}
      component: "mcmapplicationui"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "console.name" . }}
        component: "mcmapplicationui"
        release: {{ .Release.Name }}
        chart: {{ template "console.chart" . }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ template "console.name" . }}
        helm.sh/chart: {{ template "console.chart" . }}
      annotations:
        productName: "IBM Multicloud Manager - Server"
        productID: "317a72a4f22645aaa1b7a07a83c60af5"
        productVersion: "3.1.1"
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - mcmapplicationui
              topologyKey: failure-domain.beta.kubernetes.io/zone
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: mcm-application-ui
        image: "{{ .Values.mcmapplicationui.image.repository }}:{{ .Values.mcmapplicationui.image.tag }}"
        imagePullPolicy: {{ .Values.mcmapplicationui.image.pullPolicy }}
        resources:
        {{- toYaml .Values.mcmapplicationui.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: ICP_STANDALONE
          value: "{{ .Values.standalone }}"
        - name: hcmUiApiUrl
          value: https://{{ template "console.fullname" . }}-consoleapi:4000/hcmuiapi
        - name: searchApiUrl
          value: https://search-search-api:4010/searchapi
        - name: cfcRouterUrl
          value: {{ .Values.cfcRouterUrl }}
        - name: leftNav
          value: {{ .Release.Name }}-nav
        - name: PLATFORM_IDENTITY_PROVIDER_URL
          value: {{ .Values.cfcRouterUrl }}/idprovider
        - name: WLP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_ID
              name: platform-oidc-credentials
        - name: WLP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: WLP_CLIENT_SECRET
              name: platform-oidc-credentials
        ports:
        - containerPort: 3001
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livenessProbe
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readinessProbe
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      {{- if .Values.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
      {{- if .Values.nodeSelector.os }}
        "beta.kubernetes.io/os" : {{ .Values.nodeSelector.os }}
      {{- end }}
      {{- if .Values.nodeSelector.customLabelSelector }}
        {{ .Values.nodeSelector.customLabelSelector }} : {{ .Values.nodeSelector.customLabelValue}}
      {{- end }}
      {{- end }}
