# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  labels:
    app: console
    component: "console"
    chart: {{ template "console.chart" . }}
    release: {{ template "console.fullname" . }}
    heritage: {{ .Release.Service }}
data:
  CLUSTER_DISCOVERY_FEATURE_ENABLED: "true"
  CLUSTER_SET_FEATURE_ENABLED: "true"
  ASSISTED_INSTALLER_FEATURE_ENABLED: "true"
  LOG_LEVEL: default
