name: Auto trigger mch-repo

on:
  push:
    branches:
    - release-*
    paths:
    - 'stable/console-chart/**'

  workflow_dispatch:

jobs:
  notify-repo:
    runs-on: ubuntu-latest
    steps:
      # Sends a dispatch event to multicloudhub-repo to trigger an update
      - name: Notify Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: JakobGray/repo-of-charts
          event-type: chart-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          